### ISSUE TITLE
Excution Guide

### ISSUE THREAD

**Issue by KaminLee** [mccorby/PhotoLabellerServer#1]
I interested in federated learning too.
So I download your code and then tried to excute both server and client programs of Photolabeller.

In server side, , even though  the server(JobQueueServer) is executed, 
but when I hit the url to check that the server is up and running, there is an error that cannot find "currentRound.json.'

And In client app side, the application on the device is installed successfully.
And I click the "training in device" button, but the app is forced shutdown with an error. 

The error is below.================================================
06-22 10:53:26.061 16821-17063/com.mccorby.photolabeller I/System.out: org.deeplearning4j.nn.multilayer.MultiLayerNetwork@7867d03
06-22 10:53:34.740 16821-16821/com.mccorby.photolabeller I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
06-22 10:53:34.743 16821-16821/com.mccorby.photolabeller V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@52e8889
06-22 10:53:34.991 16821-16821/com.mccorby.photolabeller I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
06-22 10:53:34.996 16821-16821/com.mccorby.photolabeller I/AudioManagerEx: AudioManagerEx created
06-22 10:53:35.009 16821-16828/com.mccorby.photolabeller I/art: Do partial code cache collection, code=44KB, data=62KB
06-22 10:53:35.009 16821-16828/com.mccorby.photolabeller I/art: After code cache collection, code=43KB, data=62KB
06-22 10:53:35.010 16821-16828/com.mccorby.photolabeller I/art: Increasing code cache capacity to 256KB
06-22 10:53:35.017 16821-16821/com.mccorby.photolabeller V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@52e8889
06-22 10:53:35.017 16821-16821/com.mccorby.photolabeller V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@52e8889
06-22 10:53:35.026 16821-17287/com.mccorby.photolabeller I/System.out: Train started
06-22 10:53:35.053 16821-17287/com.mccorby.photolabeller I/System.out: []
06-22 10:53:35.063 16821-17287/com.mccorby.photolabeller W/o*.r*.Reflections: given scan urls are empty. set urls in the configuration
06-22 10:53:35.379 16821-17287/com.mccorby.photolabeller I/System.out: Epoch=====================0
06-22 10:53:35.382 16821-17287/com.mccorby.photolabeller I/System.out: next batch 16
06-22 10:53:35.382 16821-17287/com.mccorby.photolabeller I/System.out: Creating dataset for indexes 0 to 0
06-22 10:53:35.393 16821-16821/com.mccorby.photolabeller E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.mccorby.photolabeller, PID: 16821
                                                                           java.lang.IllegalArgumentException: Unable to merge empty dataset
                                                                               at org.nd4j.linalg.dataset.DataSet.merge(DataSet.java:157)
                                                                               at com.mccorby.photolabeller.trainer.ClientCifarLoader.createDataSet(ClientCifarLoader.kt:30)
                                                                               at com.mccorby.photolabeller.trainer.ClientCifarDataSetIterator.next(ClientCifarDataSetIterator.kt:17)
                                                                               at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:389)
                                                                               at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:52)
                                                                               at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:982)
                                                                               at com.mccorby.photolabeller.trainer.TrainerImpl.train(TrainerImpl.kt:87)
                                                                               at com.mccorby.photolabeller.interactor.Train.run(Train.kt:15)
                                                                               at com.mccorby.photolabeller.interactor.Train.run(Train.kt:8)
                                                                               at com.mccorby.photolabeller.interactor.UseCase$execute$job$1.doResume(UseCase.kt:13)
                                                                               at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                               at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                                                                               at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
                                                                               at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
                                                                               at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
                                                                               at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
                                                                               at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
                                                                               at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
                                                                               at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)

**Do I have to training image file in the specified directory?

So, could you tell me more sequential guide of excution this program? (both server & client)
And could you upload the additianal .json file?**

**Comment by mccorby** [comment]
Hi, This error is due to not having any samples in the client. Certainly something to check in a production app. You can try taking some photos and setting the labels and then running the trainer

**Comment by mccorby** [comment]
About the problem with the json file, you need to provide some additional information to the server.
Create a `local.properties` file in the `server` module with the following content
```
model_dir = some_directory_in_your_local_machine
# In milliseconds. 24 hours
time_window = 86400000
min_updates = 1000
layer_index = 3
```

**Comment by NilayKulkarni** [comment]
@mccorby what kind of models can be contained in the model_dir?

**Comment by jacorbachosky** [comment]
That is a destination directory. It will contain the result of training the model of the project (see CifarTrainer)

**Comment by mccorby** [comment]
Run the main method in `JobQueueServer` class

**Comment by UjumpIjump2018** [comment]
@mccorby ，I have the same problem about  missing file “currentRound.json“ in server side. And I flow your suggestion to create a local.properties file in ”server“ directory, but still not work.  And could you upload the additianal .json file? thank you!

**Comment by mccorby** [comment]
I've updated the flow in the README. I think you were missing the `create new round` step. You have to open it by going to the address
```
http://localhost:9997/service/federatedservice/currentRound
```

I added a sample JSON file as result of this operation

**Comment by UjumpIjump2018** [comment]
Thank you for your guidance, I create currentRound.json manually, it works.

**Comment by jacorbachosky** [comment]
Good news!

**Comment by mccorby** [comment]
Good news!
